apiVersion: v1
kind: Service
metadata:
  name: webui-service
  labels:
    app: free5gc
    nf: webui
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30505
  selector:
    app: free5gc
    nf: webui
